# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22c5903661d02506d80af804d251b8eac691847e15943389b69ac34fbfcf6c157248c604b1b98ca961ef90aff4d94f56efddd11c9ce7de66eee1eeb828fba1d7

test:
  secret_key_base: 6194e5b4f71c92dc1b6aaaf30e19efff192f83229a667c94e0cde245d810451701ea40b3a7c4a5ed4f4e7598e44efff8995efb535fb6db842c7a2807d92d8297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
